security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto
            cost: 4 # Valeur minimale pour bcrypt
            time_cost: 3 # Valeur minimale pour argon
            memory_cost: 10 # Valeur minimale pour argon

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        app_trader_provider:
            entity:
                class: App\Entity\Trader
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\UserAuthenticator
                - App\Security\TraderAuthenticator

            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            remember_me:
                secret: "%kernel.secret%"
                lifetime: 604800
                path: /
                always_remember_me: true

    access_control:
        # Define access control rules here
        # For example:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
